export type ObservabilityCategory =
  | "conversation"
  | "safety"
  | "post_event"
  | "admin"
  | "system"
  | "billing";

export type EventCatalogEntry = {
  event_name: string;
  category: ObservabilityCategory;
  required_fields: readonly string[];
  optional_fields: readonly string[];
  pii_fields: readonly string[];
};

export const EVENT_CATALOG: readonly EventCatalogEntry[] = [
  {
    event_name: "conversation.router_decision",
    category: "conversation",
    required_fields: ["route", "session_mode", "session_state_token"],
    optional_fields: ["request_id", "profile_is_complete_mvp", "override_applied"],
    pii_fields: [],
  },
  {
    event_name: "conversation.mode_transition",
    category: "conversation",
    required_fields: ["previous_mode", "next_mode", "reason"],
    optional_fields: ["session_id", "linkup_id", "linkup_state"],
    pii_fields: [],
  },
  {
    event_name: "conversation.state_transition",
    category: "conversation",
    required_fields: ["previous_state_token", "next_state_token", "reason"],
    optional_fields: ["session_id", "mode"],
    pii_fields: [],
  },
  {
    event_name: "safety.keyword_detected",
    category: "safety",
    required_fields: ["severity", "matched_term"],
    optional_fields: ["keyword_version", "action"],
    pii_fields: [],
  },
  {
    event_name: "safety.rate_limit_exceeded",
    category: "safety",
    required_fields: ["action"],
    optional_fields: ["window_count", "threshold", "window_start"],
    pii_fields: [],
  },
  {
    event_name: "safety.strike_applied",
    category: "safety",
    required_fields: ["strike_count", "safety_hold"],
    optional_fields: ["escalated", "severity", "action"],
    pii_fields: [],
  },
  {
    event_name: "safety.crisis_intercepted",
    category: "safety",
    required_fields: ["keyword_version", "matched_term"],
    optional_fields: ["action", "severity"],
    pii_fields: [],
  },
  {
    event_name: "safety.block_created",
    category: "safety",
    required_fields: ["blocker_user_id", "blocked_user_id"],
    optional_fields: ["linkup_id"],
    pii_fields: [],
  },
  {
    event_name: "safety.blocked_message_attempt",
    category: "safety",
    required_fields: [],
    optional_fields: ["linkup_id", "target_user_id"],
    pii_fields: [],
  },
  {
    event_name: "safety.report_created",
    category: "safety",
    required_fields: ["reporter_user_id", "reported_user_id", "reason_category"],
    optional_fields: ["incident_id", "report_reason_free_text"],
    pii_fields: ["report_reason_free_text"],
  },
  {
    event_name: "post_event.attendance_recorded",
    category: "post_event",
    required_fields: ["attendance_result", "previous_state_token", "next_state_token"],
    optional_fields: ["reason", "duplicate"],
    pii_fields: [],
  },
  {
    event_name: "post_event.learning_signal_written",
    category: "post_event",
    required_fields: ["attendance_result", "do_again"],
    optional_fields: ["linkup_id"],
    pii_fields: [],
  },
  {
    event_name: "post_event.contact_exchange_opt_in",
    category: "post_event",
    required_fields: ["exchange_choice"],
    optional_fields: ["exchange_opt_in", "mutual_detected", "reveal_sent", "blocked_by_safety"],
    pii_fields: ["contact_exchange_payload"],
  },
  {
    event_name: "post_event.contact_exchange_revealed",
    category: "post_event",
    required_fields: ["mutual_detected", "reveal_sent"],
    optional_fields: ["linkup_id", "exchange_choice"],
    pii_fields: ["contact_exchange_payload"],
  },
  {
    event_name: "admin.action_performed",
    category: "admin",
    required_fields: ["action", "target_type"],
    optional_fields: ["target_id", "metadata_json"],
    pii_fields: [],
  },
  {
    event_name: "admin.role_updated",
    category: "admin",
    required_fields: ["actor_admin_user_id", "target_user_id", "assigned_role"],
    optional_fields: [],
    pii_fields: [],
  },
  {
    event_name: "admin.safety_hold_toggled",
    category: "admin",
    required_fields: ["actor_admin_user_id", "target_user_id", "safety_hold"],
    optional_fields: ["before_state", "after_state"],
    pii_fields: [],
  },
  {
    event_name: "admin.incident_status_updated",
    category: "admin",
    required_fields: ["actor_admin_user_id", "incident_id", "before_status", "after_status"],
    optional_fields: [],
    pii_fields: [],
  },
  {
    event_name: "system.unhandled_error",
    category: "system",
    required_fields: ["phase", "error_name", "error_message"],
    optional_fields: ["stack", "status_code", "request_id"],
    pii_fields: [],
  },
  {
    event_name: "system.rpc_failure",
    category: "system",
    required_fields: ["rpc_name", "error_message"],
    optional_fields: ["request_id", "status_code"],
    pii_fields: [],
  },
  {
    event_name: "system.migration_mismatch_warning",
    category: "system",
    required_fields: ["warning"],
    optional_fields: ["details"],
    pii_fields: [],
  },
  {
    event_name: "twilio.inbound_received",
    category: "system",
    required_fields: ["inbound_message_sid"],
    optional_fields: ["command", "request_id"],
    pii_fields: [],
  },
  {
    event_name: "twilio.inbound_duplicate_sid",
    category: "system",
    required_fields: ["inbound_message_sid"],
    optional_fields: ["command", "request_id"],
    pii_fields: [],
  },
  {
    event_name: "twilio.override_applied",
    category: "system",
    required_fields: ["override_type", "inbound_message_id"],
    optional_fields: ["request_id"],
    pii_fields: [],
  },
  {
    event_name: "twilio.signature_validation_failed",
    category: "system",
    required_fields: ["host_source"],
    optional_fields: ["request_id", "method", "url", "candidates", "results"],
    pii_fields: [],
  },
  {
    event_name: "twilio.status_callback.signature_failed",
    category: "system",
    required_fields: ["host_source"],
    optional_fields: ["request_id", "method", "url", "candidates", "results"],
    pii_fields: [],
  },
  {
    event_name: "twilio.status_callback.missing_signature",
    category: "system",
    required_fields: ["request_id"],
    optional_fields: ["handler"],
    pii_fields: [],
  },
  {
    event_name: "twilio.status_callback.invalid_signature",
    category: "system",
    required_fields: ["request_id"],
    optional_fields: ["handler"],
    pii_fields: [],
  },
  {
    event_name: "twilio.status_callback.message_update_failed",
    category: "system",
    required_fields: ["message_sid", "error_message"],
    optional_fields: ["request_id"],
    pii_fields: [],
  },
  {
    event_name: "twilio.status_callback.job_update_failed",
    category: "system",
    required_fields: ["message_sid", "error_message"],
    optional_fields: ["request_id"],
    pii_fields: [],
  },
  {
    event_name: "twilio.status_callback.processed",
    category: "system",
    required_fields: ["message_sid", "message_status"],
    optional_fields: ["request_id"],
    pii_fields: [],
  },
  {
    event_name: "twilio.status_callback.unhandled_error",
    category: "system",
    required_fields: ["request_id", "phase", "error_name", "error_message"],
    optional_fields: ["stack"],
    pii_fields: [],
  },
  {
    event_name: "sms_outbound.claim_failed",
    category: "system",
    required_fields: ["error_message"],
    optional_fields: ["request_id"],
    pii_fields: [],
  },
  {
    event_name: "sms_outbound.future_job_released",
    category: "system",
    required_fields: ["job_id"],
    optional_fields: ["run_at", "purpose"],
    pii_fields: [],
  },
  {
    event_name: "sms_outbound.future_job_release_failed",
    category: "system",
    required_fields: ["job_id", "error_message"],
    optional_fields: [],
    pii_fields: [],
  },
  {
    event_name: "sms_outbound.job_update_failed",
    category: "system",
    required_fields: ["job_id", "error_message"],
    optional_fields: ["status"],
    pii_fields: [],
  },
  {
    event_name: "sms_outbound.job_failure_update_failed",
    category: "system",
    required_fields: ["job_id", "error_message"],
    optional_fields: [],
    pii_fields: [],
  },
  {
    event_name: "sms_outbound.missing_from_for_message",
    category: "system",
    required_fields: ["job_id"],
    optional_fields: [],
    pii_fields: [],
  },
  {
    event_name: "sms_outbound.sms_message_insert_failed",
    category: "system",
    required_fields: ["job_id", "error_message"],
    optional_fields: ["twilio_sid"],
    pii_fields: [],
  },
  {
    event_name: "interview_dropout.enqueue_failed",
    category: "system",
    required_fields: ["error_message"],
    optional_fields: ["request_id"],
    pii_fields: [],
  },
  {
    event_name: "interview_dropout.enqueue_summary",
    category: "system",
    required_fields: ["candidate_count", "marked_count", "enqueued_count"],
    optional_fields: ["request_id"],
    pii_fields: [],
  },
  {
    event_name: "onboarding.state_token_drift",
    category: "conversation",
    required_fields: ["routed_state_token", "persisted_state_token"],
    optional_fields: ["inbound_message_sid"],
    pii_fields: [],
  },
  {
    event_name: "onboarding.step_handler_invoked",
    category: "conversation",
    required_fields: ["step_id", "session_id"],
    optional_fields: ["correlation_id"],
    pii_fields: [],
  },
  {
    event_name: "onboarding.step_skipped",
    category: "conversation",
    required_fields: ["step_id", "session_id"],
    optional_fields: ["reason", "correlation_id"],
    pii_fields: [],
  },
  {
    event_name: "onboarding.step_sent",
    category: "conversation",
    required_fields: ["step_id", "idempotency_key"],
    optional_fields: ["correlation_id"],
    pii_fields: [],
  },
  {
    event_name: "onboarding.step_next_scheduled",
    category: "conversation",
    required_fields: ["step_id", "next_step_id"],
    optional_fields: ["delay_ms", "correlation_id"],
    pii_fields: [],
  },
  {
    event_name: "interview_extractor.call",
    category: "system",
    required_fields: ["prompt_version", "attempt"],
    optional_fields: ["correlation_id"],
    pii_fields: [],
  },
  {
    event_name: "interview_extractor.output_rejected",
    category: "system",
    required_fields: ["prompt_version", "attempt"],
    optional_fields: ["correlation_id", "violation_codes"],
    pii_fields: [],
  },
  {
    event_name: "interview_extractor.failure",
    category: "system",
    required_fields: ["prompt_version", "attempt"],
    optional_fields: ["correlation_id", "code", "transient", "error_message"],
    pii_fields: [],
  },
  {
    event_name: "messaging.send.non_retryable_4xx",
    category: "system",
    required_fields: ["status_code", "idempotency_key"],
    optional_fields: ["purpose"],
    pii_fields: [],
  },
  {
    event_name: "messaging.send.retrying_once",
    category: "system",
    required_fields: ["status_code", "idempotency_key", "attempt"],
    optional_fields: ["purpose"],
    pii_fields: [],
  },
  {
    event_name: "cron.invoked",
    category: "system",
    required_fields: ["handler"],
    optional_fields: ["request_id"],
    pii_fields: [],
  },
  {
    event_name: "cron.missing_secret",
    category: "system",
    required_fields: ["handler"],
    optional_fields: ["request_id"],
    pii_fields: [],
  },
  {
    event_name: "cron.unauthorized",
    category: "system",
    required_fields: ["handler"],
    optional_fields: ["request_id"],
    pii_fields: [],
  },
  {
    event_name: "cron.invalid_vercel_header",
    category: "system",
    required_fields: ["handler"],
    optional_fields: ["request_id"],
    pii_fields: [],
  },
  {
    event_name: "cron.sentry_test",
    category: "system",
    required_fields: ["handler"],
    optional_fields: ["request_id"],
    pii_fields: [],
  },
  {
    event_name: "cron.missing_runner_url",
    category: "system",
    required_fields: ["handler"],
    optional_fields: ["request_id"],
    pii_fields: [],
  },
  {
    event_name: "cron.runner_url_invalid",
    category: "system",
    required_fields: ["handler"],
    optional_fields: ["request_id"],
    pii_fields: [],
  },
  {
    event_name: "cron.missing_runner_secret",
    category: "system",
    required_fields: ["handler"],
    optional_fields: ["request_id"],
    pii_fields: [],
  },
  {
    event_name: "cron.runner_unreachable",
    category: "system",
    required_fields: ["handler"],
    optional_fields: ["request_id", "status_code"],
    pii_fields: [],
  },
  {
    event_name: "cron.runner_summary",
    category: "system",
    required_fields: ["handler", "status_code"],
    optional_fields: ["request_id"],
    pii_fields: [],
  },
  {
    event_name: "cron.runner_response",
    category: "system",
    required_fields: ["handler", "status_code"],
    optional_fields: ["request_id"],
    pii_fields: [],
  },
  {
    event_name: "reconcile.invoked",
    category: "system",
    required_fields: ["handler"],
    optional_fields: ["request_id"],
    pii_fields: [],
  },
  {
    event_name: "reconcile.twilio_fetch_failed",
    category: "system",
    required_fields: ["message_sid"],
    optional_fields: ["request_id", "status_code", "error_message"],
    pii_fields: [],
  },
  {
    event_name: "reconcile.twilio_missing_status",
    category: "system",
    required_fields: ["message_sid"],
    optional_fields: ["request_id"],
    pii_fields: [],
  },
  {
    event_name: "reconcile.db_update_failed",
    category: "system",
    required_fields: ["message_sid", "error_message"],
    optional_fields: ["request_id"],
    pii_fields: [],
  },
  {
    event_name: "reconcile.summary",
    category: "system",
    required_fields: ["handler"],
    optional_fields: ["request_id", "checked", "updated", "skipped", "failed"],
    pii_fields: [],
  },
  {
    event_name: "reconcile.unhandled_error",
    category: "system",
    required_fields: ["handler", "error_message"],
    optional_fields: ["request_id", "error_name"],
    pii_fields: [],
  },
  {
    event_name: "stripe.checkout.create_failed",
    category: "billing",
    required_fields: ["error_message"],
    optional_fields: ["request_id"],
    pii_fields: [],
  },
  {
    event_name: "stripe.portal.create_failed",
    category: "billing",
    required_fields: ["error_message"],
    optional_fields: ["request_id"],
    pii_fields: [],
  },
  {
    event_name: "stripe.webhook.invalid_signature",
    category: "billing",
    required_fields: [],
    optional_fields: ["request_id", "error_message"],
    pii_fields: [],
  },
  {
    event_name: "stripe.webhook.signature_verification_failed",
    category: "billing",
    required_fields: ["error_message"],
    optional_fields: ["request_id"],
    pii_fields: [],
  },
  {
    event_name: "stripe.webhook.duplicate",
    category: "billing",
    required_fields: ["stripe_event_id"],
    optional_fields: ["request_id"],
    pii_fields: [],
  },
  {
    event_name: "stripe.webhook.ingested",
    category: "billing",
    required_fields: ["stripe_event_id", "stripe_event_type"],
    optional_fields: ["request_id"],
    pii_fields: [],
  },
  {
    event_name: "stripe.webhook.mark_failed_write_error",
    category: "billing",
    required_fields: ["stripe_event_id", "error_message"],
    optional_fields: ["request_id"],
    pii_fields: [],
  },
  {
    event_name: "stripe.webhook.ingest_failed",
    category: "billing",
    required_fields: ["error_message"],
    optional_fields: ["request_id"],
    pii_fields: [],
  },
] as const;

const eventCatalogByName = Object.create(null) as Record<string, EventCatalogEntry>;
for (const eventEntry of EVENT_CATALOG) {
  eventCatalogByName[eventEntry.event_name] = eventEntry;
}

export const EVENT_CATALOG_BY_NAME: Readonly<Record<string, EventCatalogEntry>> =
  eventCatalogByName;

export type CanonicalEventName = (typeof EVENT_CATALOG)[number]["event_name"];
