import { describe, expect, it } from "vitest";
import {
  interviewDropoutNudgeTemplate,
  interviewDropoutResume,
  interviewWrap,
  linkupLockConfirmation,
  onboardingBurstMessage1,
  onboardingBurstMessage2,
  onboardingBurstMessage3,
  onboardingBurstMessage4,
  onboardingExplanation,
  onboardingLater,
  onboardingOpeningTemplate,
  postEventDoAgainClarifier,
  postEventDoAgainMessage,
  postEventFeedbackMessage,
  safetyCrisisResources,
  safetyHoldNotification,
  safetyReportConfirmation,
  safetyReportPrompt,
  systemHelpResponse,
  systemUnknownIntentResponse,
  renderInterviewDropoutNudgeMessage,
  renderLinkupCoordinationMessage,
  renderLinkupInviteMessage,
  renderLinkupReminderMessage,
  renderOnboardingOpeningMessage,
  renderPostEventAttendanceMessage,
  renderPostEventContactIntroMessage,
  renderPostEventContactRevealMessage,
  renderPostEventDropoutNudgeMessage,
  renderSafetyBlockConfirmation,
  renderSystemOtpMessage,
} from "../index";

describe("messaging templates snapshots", () => {
  it("renders all template categories with stable copy", () => {
    expect({
      onboarding_opening_template: onboardingOpeningTemplate(),
      onboarding_opening_rendered: renderOnboardingOpeningMessage({ firstName: "Avery" }),
      onboarding_explanation: onboardingExplanation(),
      onboarding_message_1: onboardingBurstMessage1(),
      onboarding_message_2: onboardingBurstMessage2(),
      onboarding_message_3: onboardingBurstMessage3(),
      onboarding_message_4: onboardingBurstMessage4(),
      onboarding_later: onboardingLater(),
      interview_wrap: interviewWrap(),
      interview_dropout_nudge_template: interviewDropoutNudgeTemplate(),
      interview_dropout_nudge_rendered: renderInterviewDropoutNudgeMessage({ firstName: "Avery" }),
      interview_dropout_resume: interviewDropoutResume(),
      linkup_invite: renderLinkupInviteMessage({
        firstName: "Avery",
        activityName: "brunch",
        whenText: "this Saturday at 11am",
      }),
      linkup_lock_confirmation: linkupLockConfirmation(),
      linkup_reminder: renderLinkupReminderMessage({
        activityName: "brunch",
        startsAtText: "in 2 hours",
      }),
      linkup_coordination: renderLinkupCoordinationMessage({
        activityName: "brunch",
        locationName: "Southside Cafe",
        startsAtText: "Saturday at 11:00 AM",
      }),
      post_event_attendance: renderPostEventAttendanceMessage({
        firstName: "Avery",
        activityName: "brunch",
      }),
      post_event_do_again: postEventDoAgainMessage(),
      post_event_do_again_clarifier: postEventDoAgainClarifier(),
      post_event_feedback: postEventFeedbackMessage(),
      post_event_dropout_nudge: renderPostEventDropoutNudgeMessage({ firstName: "Avery" }),
      post_event_contact_intro: renderPostEventContactIntroMessage({ activityName: "brunch" }),
      post_event_contact_reveal: renderPostEventContactRevealMessage({
        otherFirstName: "Jordan",
        phoneE164Formatted: "+1 (555) 444-0099",
      }),
      safety_crisis_resources: safetyCrisisResources(),
      safety_hold_notification: safetyHoldNotification(),
      safety_block_confirmation: renderSafetyBlockConfirmation({ name: "Jordan" }),
      safety_report_prompt: safetyReportPrompt(),
      safety_report_confirmation: safetyReportConfirmation(),
      system_otp: renderSystemOtpMessage({ code: "123456", expiresInMinutes: 10 }),
      system_help_response: systemHelpResponse(),
      system_unknown_intent_response: systemUnknownIntentResponse(),
    }).toMatchSnapshot();
  });
});
